[package]
name = "aicc"
version = "0.1.0"
edition = "2024"

[dependencies]
antlr-rust = "0.3.0-beta"
inline-xml = "0.3.2"
ogrim = "0.1.1"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.16"
toml = "0.9.5"
xmltree = "0.11.0"
